### ISSUE TITLE
Code generation fails on _StringStackTrace with typeAnnotationDeepQuantifyCapability

### ISSUE THREAD

**Issue by hyperrecursive** [google/reflectable.dart#214]
Hello, first of all, thank you for your work. I find this package very well written and documented.

I have the following problem - whenever I add `typeAnnotationDeepQuantifyCapability` to my reflector, code generation fails with:

```
[SEVERE] reflectable:reflectable on lib/main_dev.dart:
dart:core/stacktrace.dart:: Cannot access private name _StringStackTrace
```

Unfortunately, I am not able to trace the root of the problem, as StackTrace is not annotated by @reflector, nor it is a field or an argument to a method of any of the annotated types. I have `stack_trace: ^1.9.3` in my `pubspec.yaml`.

Could you help me to solve the problem, please?

**Comment by hyperrecursive** [comment]
Unfortunately, removing `stack_trace` from `pubspec.yaml` renders the same error.

**Comment by hyperrecursive** [comment]
To give a better overview, I want to be able to get a return type of a method.

```
@reflector
class A {
    FutureOr<T> get<T>(String caller) {
        var reflection = reflector.reflect(this);
        var returnType = reflection.type.instanceMembers[caller].returnType;
        ...
    }
}

@reflector
class B extends A {
    FutureOr<List<C>> doWork() {
        return await get<List<C>>('doWork');
    }
}

@reflector
class C { ... }
```

As far as I understood, I need to reflect List, and for that, I need `typeAnnotationDeepQuantifyCapability`. Maybe there is another way that I can use to reflect the return type of an instance method?

**Comment by eernstg** [comment]
It does not sound like you need to request `typeAnnotationDeepQuantifyCapability`, that is a feature which is intended for including reflection support for the transitive closure of type annotations. Ex:

```dart
@reflector 
class A {
  B get b => B();
}

class B {
  void foo(C c) {}
}
```

If `@reflector` causes class `A` to be covered, and you include `typeAnnotationQuantifyCapability` (NB: not `Deep`) and `reflectedTypeCapability` then you can call methods like `declarations`, `instanceMembers`, `staticMembers` on a class mirror, and you can use `reflectedReturnType` on a method mirror, e.g., comparing that like `myMethodMirror.reflectedReturnType == B`.

With `Deep` you will also cause `reflector` to cover class `B`, and class `C`, and so on, because `Deep` is concerned with paths of any length (where each edge is from a class to a type annotation in that class).

So the first thing to try is to avoid `Deep`.

The next issue is that you seem to require some capabilities that make it absolutely necessary to support access to a private class (perhaps because you request the ability to create a new instance of a private class or something like that), so if you really must have `Deep` then it may be tricky to avoid the issue, because there is no support for "trace paths of any length, and do something magical when you encounter a private class". ;-)

**Comment by hyperrecursive** [comment]
Using `typeAnnotationQuantifyCapability` with `reflectedTypeCapability` worked, thank you very much for your support.
