### ISSUE TITLE
How to instantiate an object of type T ?

### ISSUE THREAD

**Issue by maxime-aubry** [google/reflectable.dart#225]
Hello.
I use reflectable for my project.
I try to instantiate an object using by the generic type only. There are two constructors. One of them has parameters.
Can you help me please ?
I don't find help on your documentation.
Thanks.

**Comment by eernstg** [comment]
What is `T`? It sounds like you're trying to create an instance of the value of a type parameter. That is basically not possible in Dart.

First, you cannot create an instance of the value of a type parameter in Dart, even if that type parameter is in scope (such that you would be able to write `new T(42)` or something like that). So even without the need for reflection in the first place, you wouldn't be able to create the instance.

(That wouldn't work in many cases anyway: We can't "create a new `int`", we'd have to provide an existing one, and you can't create an instance of an abstract class, etc.)

Second, Reflectable is based on generated code, and there is no mechanism in Dart which allows code to obtain the value of the actual type arguments of a given object. So if you have an object `o` which is a `List<int>`, but the static type is, for instance, `Object` or `Iterable<num>`, there is no way you can obtain the type argument `int` and use that as a type.

I think you'd need to look into dependency injection in order to do the kind of thing that you're describing.

**Comment by eernstg** [comment]
I'll close this issue, because it's far removed from the intended and implementable functionality of reflectable.
