### ISSUE TITLE
How to use multiple reflectors in one project

### ISSUE THREAD

**Issue by maxime-aubry** [google/reflectable.dart#226]
Hello.

I try to use multiple reflectors in my project.
When I get InstanceMirror of my first object, all is fine.
When I get InstanceMirror of my second object, all is fine too.
But, just after, I get an Exception NoSuchCapabilityError 'Reflecting on un-marked type ...'.
All my reflectors are in myfile.reflectable.dart.
I think that when I reflect an object, the previous one is erased. But I am not dure.

**Comment by eernstg** [comment]
There's no way to erase a mirror or an object, but you get `NoSuchCapabilityError` if the mirror you're using belongs to a reflector that doesn't specify the required capability.

In general, you can use multiple reflectors, but it is a specialized mechanism so it's worth considering whether you actually want to use it.

In particular, each reflector has its own "universe" of mirrors, with specific capabilities and targets. If you have two reflectors, `reflector1` and `reflector2`, a mirror created with `reflector1` will have the capabilities specified by `reflector1` and not the ones specified by `reflector2`; so a reflector1-mirror might be able to invoke methods and a reflector2-mirror might be able to traverse the superclass chain of a class. Unless you actually want to partition your mirrors into different kinds like this, it is more likely to work well if you just have a single reflector, and use that to provide all the capabilities you need, on all the targets you wish to cover.

Otherwise, multiple reflectors can be used to save space in the case where different parts of the program use reflectable in  different ways. Here's a small example that uses 8 different reflectors: https://github.com/google/reflectable.dart/blob/master/test_reflectable/test/corresponding_setter_test.dart.

In the example, `InvokingMetaReflector` uses `InvokingMetaCapability(P)` to provide invocation support for all methods carrying the metadata `@P` in classes covered (by having metadata `@invokingMetaCapability`, typically).

Similarly, `StaticInvokeFrReflector` supports only invocation of static methods, and only the ones whose name matches `methodRegExp`.

If you have a large program you can use this to support invocation in a more general manner with a few classes (marking them with `InvokingMetaReflector`), and you could use `StaticInvokeFrReflector` to get a much lower level of support (just some static methods) for a large number of classes, and then you'd save space on the mirror data as a whole.

**Comment by eernstg** [comment]
I think we haven't found any issues with the use of multiple reflectors in one project, so I'll close this issue.
