### ISSUE TITLE
Reflectable in a Flutter package

### ISSUE THREAD

**Issue by TomasWeg** [google/reflectable.dart#244]
Hello. I just want to know how to implement reflectable in a Flutter library which will be delivered to pub.dev.

I run the build command and generates a file with the following content:
```
// No output from reflectable, there is no `main`.
```

**Comment by eernstg** [comment]
Presumably you would determine which parts of the program need to get reflection support, in which ways, by declaring a `class Reflector extends Reflectable ...` in some library _L_ in your package, and (for convenience) `const reflector = Reflector();`.

Reflectable allows for having, for instance, `@reflector class C {...}` in any library that imports _L_. So let's say that a package _P_ uses your package and declares such a class.

This means that it is not possible in an approach based on code generation (like reflectable) to generate the required code in order to support reflection on that class `C` using only your package: Nothing in your package knows anything about the existence of the package _P_.

So, in general, you would need to ask your clients to run the reflectable code generation step, if you wish to obtain reflection support for anything outside your own package.

On the other hand, if you do not wish to make it possible for clients to obtain reflection support for anything _they_ have written, they only get reflection support for a number of things declared in your package (or imported into your package) then you can do it as follows:

In your `bin` directory (or anywhere else as long as it is outside your package itself), write a minimal client entry point _L0_ (that is, a library that contains a `main` function), let's call it `bin/minimal_client.dart`.

`bin/minimal_client.dart` imports (directly or indirectly) the libraries from your package that you want to obtain reflection support for. Then generate code for `bin/minimal_client.dart`. Then move the generated file into your package, say, into `lib/src/reflector_data.reflectable.dart`, and make sure that it is imported by some library in your package that calls `initializeReflectable()` at start-up.

With that, you can obtain support for reflection with some classes and/or other entities in your own package, and you can enable the use of reflection in your package as well as in client libraries (but only on those entities from your package that you have generated code for).

You would make `lib/src/reflector_data.reflectable.dart` part of your package, it would be created afresh by you each time you publish your package (such that it is kept in sync with the declarations that you wish to enable reflection for).

So it's definitely possible, and it might work just fine for you. But the approach will _only_ allow for reflection to be applied to instances of your classes and declarations in your libraries; if you need reflection also for client-declared classes and functions etc. then you'll have to ask your clients to run the reflectable code generator themselves.

I think I'll close the issue: The approach I've described _can_ be used if you can live with the limitations, and on the other hand it's inherently impossible to obtain generated code that describes a class that the code generator has never seen.

**Comment by TomasWeg** [comment]
@eernstg I made it to work but I have another question and maybe you can help.

```dart
@reflection
typedef Where<T> = bool Function(T);
```

The following is not working when I try to get:
```dart
var whereMirror = reflection.reflect(whereExpr);
```

This is my Reflection class:

```dart
class Reflection extends Reflectable {
  const Reflection() : super(invokingCapability, reflectedTypeCapability, typeAnnotationDeepQuantifyCapability);
}
```

**Comment by eernstg** [comment]
@TomasWeg, there is unfortunately almost no support for reflection on functions. The README says it as follows, in the list of unsupported things:

> Reflection on functions/closures. We do not have the required primitives
> to support this feature, so it is expected to remain unsupported for a
> while. There is support for one case: When a function type is given a name
> with typedef it is possible to use that name as a type annotation, say, on a
> method parameter or as a return type, and then reflectedTypeCapability
> will make it possible to get a corresponding reflectedType and
> `dynamicReflectedType`. For non-generic function types this will also
> work with anonymous (inline) function types like void Function(int).

So there is simply no way in Dart for an approach based on code generation to produce a representation of the return type or any formal parameter type of a given function type, or otherwise to decompose the function type.

You can of course obtain the function type from a function using `runtimeType`, and you can use `is` on a function to compare its type with a given function type. This will allow you to make distinctions among functions with different argument list shapes, e.g.:

```dart
class FunctionTypeMatcher<X> {
  X Function(Function(Never, Never, [Never, Never]))? on22;
  X Function(Function(Never, Never, [Never]))? on21;
  X Function(Function(Never, Never))?  on20;
  X Function(Function(Never, [Never, Never]))?  on12;
  X Function(Function(Never, [Never]))?  on11;
  X Function(Function(Never))?  on10;
  X Function(Function([Never, Never]))?  on02;
  X Function(Function([Never]))?  on01;
  X Function(Function())?  on00;
  X Function(Function)? onOther;

  FunctionTypeMatcher({this.on22, this.on21, this.on20, this.on12,
      this.on11, this.on10, this.on02, this.on01, this.on00, this.onOther});

  X? call(Function f) {
    if (f is Function(Never, Never, [Never, Never])) return on22?.call(f);
    if (f is Function(Never, Never, [Never])) return on21?.call(f);
    if (f is Function(Never, Never)) return on20?.call(f);
    if (f is Function(Never, [Never, Never])) return on12?.call(f);
    if (f is Function(Never, [Never])) return on11?.call(f);
    if (f is Function(Never)) return on10?.call(f);
    if (f is Function([Never, Never])) return on02?.call(f);
    if (f is Function([Never])) return on01?.call(f);
    if (f is Function()) return on00?.call(f);
    return onOther?.call(f);
  }
}

String foo(int i) => 'x$i';

void main() {
  Function g = foo; // So you have obtained a function, somehow, with unknown type.

  // `FunctionTypeMatcher` allows us to specify what to do for specific argument
  // list shapes. Let's cover `on10`: One required positional + one optional positional.
  String? s = FunctionTypeMatcher<String>(on10: (dynamic f) => f(42))(g);
  print(s);
}
```

This won't tell you which named parameters any given function or function type has, but it does allow for a small amount of programmatic detection of the structure of a function type.
